"""NIST OSCAL document serializer for FedRAMP compliance submissions.

GAP-303: OSCAL Export.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any


class OSCALExporter:
    """Serializes AumOS control data to NIST OSCAL format (version 1.1.2).

    FedRAMP PMO requires OSCAL submissions since November 2023.
    Supports JSON serialization (preferred over XML for FedRAMP tooling).

    Document types supported:
    - assessment-results: Control assessment findings
    - plan-of-action-and-milestones (POA&M): Remediation tracking
    - system-security-plan: Generated by SSPGenerator adapter
    """

    OSCAL_SCHEMA_VERSION = "1.1.2"

    def export_assessment_results(
        self,
        controls: list[dict],
        assessment_metadata: dict,
    ) -> dict[str, Any]:
        """Generate OSCAL Assessment Results from control status data.

        Args:
            controls: List of {control_id, status, implementation_narrative} dicts.
            assessment_metadata: assessor, assessment_date, impact_level, system_name.

        Returns:
            OSCAL assessment-results JSON document (1.1.2).
        """
        findings = [
            {
                "uuid": str(uuid.uuid4()),
                "title": f"Control {c['control_id']} Assessment",
                "description": c.get("implementation_narrative", ""),
                "target": {
                    "type": "statement-id",
                    "target-id": f"{c['control_id']}-stmt",
                    "status": {
                        "state": "satisfied"
                        if c.get("status") == "IMPLEMENTED"
                        else "not-satisfied"
                    },
                },
            }
            for c in controls
        ]

        return {
            "assessment-results": {
                "uuid": str(uuid.uuid4()),
                "metadata": {
                    "title": (
                        f"FedRAMP Assessment Results - "
                        f"{assessment_metadata.get('system_name', 'AumOS')}"
                    ),
                    "last-modified": datetime.now(timezone.utc).isoformat(),
                    "version": "1.0",
                    "oscal-version": self.OSCAL_SCHEMA_VERSION,
                },
                "results": [
                    {
                        "uuid": str(uuid.uuid4()),
                        "title": "FedRAMP Annual Assessment",
                        "description": f"Assessment of {len(controls)} controls",
                        "start": assessment_metadata.get(
                            "assessment_date",
                            datetime.now(timezone.utc).isoformat(),
                        ),
                        "end": datetime.now(timezone.utc).isoformat(),
                        "findings": findings,
                    }
                ],
            }
        }

    def export_poam(self, poam_items: list[dict]) -> dict[str, Any]:
        """Generate OSCAL Plan of Action and Milestones document.

        FedRAMP remediation timelines enforced:
        - Critical: 30 days
        - High: 90 days
        - Moderate: 180 days
        - Low: 365 days

        Args:
            poam_items: List of {finding_id, risk_level, description,
                        remediation_steps, due_date} dicts.

        Returns:
            OSCAL poam JSON document (1.1.2).
        """
        return {
            "plan-of-action-and-milestones": {
                "uuid": str(uuid.uuid4()),
                "metadata": {
                    "title": "FedRAMP Plan of Action and Milestones",
                    "last-modified": datetime.now(timezone.utc).isoformat(),
                    "version": "1.0",
                    "oscal-version": self.OSCAL_SCHEMA_VERSION,
                },
                "risks": [
                    {
                        "uuid": str(uuid.uuid4()),
                        "title": item["description"][:100],
                        "description": item["description"],
                        "status": {"state": "open"},
                        "characterizations": [
                            {
                                "facets": [
                                    {
                                        "name": "likelihood",
                                        "system": "https://fedramp.gov",
                                        "value": item.get("risk_level", "medium"),
                                    }
                                ]
                            }
                        ],
                    }
                    for item in poam_items
                ],
            }
        }

    def export_catalog(self, control_families: list[dict]) -> dict[str, Any]:
        """Generate an OSCAL catalog from control family definitions.

        Args:
            control_families: List of control family dicts with controls.

        Returns:
            OSCAL catalog JSON document (1.1.2).
        """
        return {
            "catalog": {
                "uuid": str(uuid.uuid4()),
                "metadata": {
                    "title": "AumOS NIST 800-53 Rev5 Implementation Catalog",
                    "last-modified": datetime.now(timezone.utc).isoformat(),
                    "version": "1.0",
                    "oscal-version": self.OSCAL_SCHEMA_VERSION,
                },
                "groups": [
                    {
                        "id": family.get("family_id", ""),
                        "title": family.get("family_name", ""),
                        "controls": [
                            {
                                "id": ctrl.get("control_id", ""),
                                "title": ctrl.get("control_name", ""),
                                "parts": [
                                    {
                                        "id": f"{ctrl.get('control_id', '')}-stmt",
                                        "name": "statement",
                                        "prose": ctrl.get("implementation_narrative", ""),
                                    }
                                ],
                            }
                            for ctrl in family.get("controls", [])
                        ],
                    }
                    for family in control_families
                ],
            }
        }
